# Generated by Django 5.0.6 on 2024-06-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrow_date_before_expected_return_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual_return_date_after_borrow_date",
        ),
    ]
