# Generated by Django 5.0.6 on 2024-07-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="borrowings.borrowing",
            ),
        ),
    ]
