# Generated by Django 5.0.6 on 2024-07-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0006_rename_borrowing_id_payment_borrowing"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrow_date_before_or_equal_expected",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual_return_date_after_borrow_date",
        ),
    ]
