# Generated by Django 5.0.6 on 2024-07-02 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        (
            "borrowings",
            "0007_remove_borrowing_borrow_date_before_or_equal_expected_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "borrowing_date__lte",
                        models.F("expected_returning_date"),
                    )
                ),
                name="borrow_date_before_or_equal_expected",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("actual_returning_date__gte", models.F("borrowing_date"))
                ),
                name="actual_return_date_after_borrow_date",
            ),
        ),
    ]
